spring.application.name=api-gateway

# Puerto del Gateway
server.port=8080

# Configuracion de EUREKA
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

#CLIENTES

# Ruta para el microservicio de CLIENTES
spring.cloud.gateway.server.webflux.routes[0].id=clientes
spring.cloud.gateway.server.webflux.routes[0].uri=lb://clientes-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/clientes/**

# Ruta para el microservicio de EMPRESAS
spring.cloud.gateway.server.webflux.routes[1].id=empresas
spring.cloud.gateway.server.webflux.routes[1].uri=lb://clientes-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/empresas/**

# Ruta para el microservicio de MARCAS
spring.cloud.gateway.server.webflux.routes[2].id=marcas
spring.cloud.gateway.server.webflux.routes[2].uri=lb://productos-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/marcas/**

# Ruta para el microservicio de PRODUCTOS
spring.cloud.gateway.server.webflux.routes[3].id=productos
spring.cloud.gateway.server.webflux.routes[3].uri=lb://productos-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/productos/**

# Ruta para el microservicio de SUCURSALES
spring.cloud.gateway.server.webflux.routes[4].id=sucursales
spring.cloud.gateway.server.webflux.routes[4].uri=lb://empleados-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/v1/sucursales/**

# Ruta para el microservicio de EMPLEADOS
spring.cloud.gateway.server.webflux.routes[5].id=empleados
spring.cloud.gateway.server.webflux.routes[5].uri=lb://empleados-service
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/v1/empleados/**

# Ruta para el microservicio de INVENTARIOS
spring.cloud.gateway.server.webflux.routes[6].id=inventarios
spring.cloud.gateway.server.webflux.routes[6].uri=lb://inventario-service
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/v1/inventario/**

# Ruta para el microservicio de PROVEEDOR
spring.cloud.gateway.server.webflux.routes[7].id=proveedores
spring.cloud.gateway.server.webflux.routes[7].uri=lb://proveedores-service
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/v1/proveedores/**

# Ruta para el microservicio de CONTACTO-PROVEEDOR
spring.cloud.gateway.server.webflux.routes[8].id=contacto_proveedores
spring.cloud.gateway.server.webflux.routes[8].uri=lb://proveedores-service
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=api/v1/contactoproveedores/**

# Repetir ruta para cada micoservicio faltante





