# Puerto del Gateway
server.port=8080

spring.cloud.gateway.globalcors.add-to-status-block=true
spring.cloud.gateway.default-filters[0]=DeduplicateResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
spring.cloud.gateway.x-forwarded.enabled=true

# Configuracion de EUREKA
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

#CLIENTES

# Ruta para el microservicio de CLIENTES
spring.cloud.gateway.routes[0].id=clientes
spring.cloud.gateway.routes[0].uri=lb://clientes-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/clientes/**

# Ruta para el microservicio de EMPRESAS
spring.cloud.gateway.routes[1].id=empresas
spring.cloud.gateway.routes[1].uri=lb://clientes-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/empresas/**

# Ruta para el microservicio de MARCAS
spring.cloud.gateway.routes[2].id=marcas
spring.cloud.gateway.routes[2].uri=lb://productos-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/marcas/**

# Ruta para el microservicio de PRODUCTOS
spring.cloud.gateway.routes[3].id=productos
spring.cloud.gateway.routes[3].uri=lb://productos-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/productos/**

# Ruta para el microservicio de SUCURSALES
spring.cloud.gateway.routes[4].id=empleados-swagger
spring.cloud.gateway.routes[4].uri=lb://empleados-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/empleados-service/v3/api-docs/**, /empleados-service/swagger-ui/**, /empleados-service/v3/api-docs/swagger-config
spring.cloud.gateway.routes[4].filters[0]=StripPrefix=1

# Ruta para el microservicio de SUCURSALES
spring.cloud.gateway.routes[5].id=sucursales
spring.cloud.gateway.routes[5].uri=lb://empleados-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/sucursales/**

# Ruta para el microservicio de EMPLEADOS
spring.cloud.gateway.routes[6].id=empleados
spring.cloud.gateway.routes[6].uri=lb://empleados-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/v1/empleados/**

# Ruta para el microservicio de INVENTARIOS
spring.cloud.gateway.routes[7].id=inventarios
spring.cloud.gateway.routes[7].uri=lb://inventario-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/v1/inventario/**

# Ruta para el microservicio de PROVEEDOR
spring.cloud.gateway.routes[8].id=proveedores-swagger
spring.cloud.gateway.routes[8].uri=lb://proveedores-service
spring.cloud.gateway.routes[8].predicates[0]=Path=/proveedores-service/v3/api-docs/**, /proveedores-service/swagger-ui/**, /proveedores-service/v3/api-docs/swagger-config
spring.cloud.gateway.routes[8].filters[0]=StripPrefix=1

# Ruta para el microservicio de PROVEEDOR
spring.cloud.gateway.routes[9].id=proveedores
spring.cloud.gateway.routes[9].uri=lb://proveedores-service
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/v1/proveedores/**

# Ruta para el microservicio de CONTACTO-PROVEEDOR
spring.cloud.gateway.routes[10].id=contacto_proveedores
spring.cloud.gateway.routes[10].uri=lb://proveedores-service
spring.cloud.gateway.routes[10].predicates[0]=Path=/api/v1/contactoproveedores/**

# Ruta para el microservicio de ORDENES
spring.cloud.gateway.routes[11].id=orden_compra
spring.cloud.gateway.routes[11].uri=lb://ordenes-service
spring.cloud.gateway.routes[11].predicates[0]=Path=/api/v1/ordenes/**

# Ruta para el microservicio de DETALLES-ORDENES
spring.cloud.gateway.routes[12].id=detalle_orden
spring.cloud.gateway.routes[12].uri=lb://ordenes-service
spring.cloud.gateway.routes[12].predicates[0]=Path=/api/v1/detalles/**

# Ruta para el microservicio de FACTURAS
spring.cloud.gateway.routes[13].id=facturas
spring.cloud.gateway.routes[13].uri=lb://facturacion-service
spring.cloud.gateway.routes[13].predicates[0]=Path=/api/v1/facturas/**

# Ruta para el microservicio de FACTURAS
spring.cloud.gateway.routes[14].id=facturacion-swagger
spring.cloud.gateway.routes[14].uri=lb://facturacion-service
spring.cloud.gateway.routes[14].predicates[0]=Path=/facturacion-service/v3/api-docs/**, /facturacion-service/swagger-ui/**, /facturacion-service/v3/api-docs/swagger-config
spring.cloud.gateway.routes[14].filters[0]=StripPrefix=1

# Ruta para el microservicio de ENVIOS
spring.cloud.gateway.routes[15].id=envios
spring.cloud.gateway.routes[15].uri=lb://envios-service
spring.cloud.gateway.routes[15].predicates[0]=Path=/api/v1/envios/**

# Ruta para el microservicio de ENVIOS
spring.cloud.gateway.routes[16].id=envios-swagger
spring.cloud.gateway.routes[16].uri=lb://envios-service
spring.cloud.gateway.routes[16].predicates[0]=Path=/envios-service/v3/api-docs/**, /envios-service/swagger-ui/**, /envios-service/v3/api-docs/swagger-config
spring.cloud.gateway.routes[16].filters[0]=StripPrefix=1