server.port=0

#Configuración de BD
spring.datasource.url=jdbc:mysql://localhost:3306/bd_facturacion
spring.datasource.username=root
spring.datasource.password=

#Configuración SPRING y MYSQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql = true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuracion eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.instance-id=${spring.application.name}:${random.value}
eureka.instance.prefer-ip-address=true

#Configuracion Swagger
spring.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.config-url=/facturacion-service/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/facturacion-service/v3/api-docs
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

server.forward-headers-strategy=framework

springdoc.openapi.servers[0].url=/facturacion-service
springdoc.openapi.servers[0].description=API Gateway - Facturas